### ISSUE TITLE
Running issue with latest node & npm version.

### ISSUE THREAD

**Issue by tnchuntic** [danmindru/responsive-html-email-signature#56]
Just want to reach out if the email signature template is compatible with latest version of node & npm ? or it should be set to a specific versions.

Thanks

Hi there, please provide some info about your enviornment before submiting this issue:
- device        : Mac
- OS            : OSX
- email client  :
- node version  : 10.15.3
- npm version   : 6.4.1
- error message : ReferenceError: internalBinding is not defined

**Comment by paskainos** [comment]
I just ran into the same issue. Was working, and broke after npm update.

Output:

```bash
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ ([PATH_TO]/node_modules/natives/index.js:137:5)
    at Object.req [as require] ([PATH_TO]/node_modules/natives/index.js:54:10)
    at Object.<anonymous> ([PATH_TO]/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
```

A quick search found this [related comment](https://github.com/gulpjs/gulp/issues/2246#issuecomment-435646661) and fix:

> Update to natives@1.1.6. Run ```npm install natives@1.1.6.```

**Comment by danmindru** [comment]
Thanks for the heads up!
I’ll take a look and perhaps update other dependencies as well while I am at it.

**Comment by danmindru** [comment]
@tnchuntic @paskainos should be fine now. Let me know if you have other problems.
