### ISSUE TITLE
primordials is not defined

### ISSUE THREAD

**Issue by NoWorries** [danmindru/responsive-html-email-signature#65]
- device        : Macbook Pro
- OS            : 10.14.6
- email client  : n/a
- node version  : v12.8.1
- npm version   : 6.11.2
- error message :

Trying to make some new signatures with templates that worked earlier in the year. `gulp` fails with following message:

```
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/joshharwood/Sites/signature-generator/responsive-html-email-signature/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/joshharwood/Sites/signature-generator/responsive-html-email-signature/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/joshharwood/Sites/signature-generator/responsive-html-email-signature/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
```

**Comment by danmindru** [comment]
Thanks for the report. It might be related to node v12. I don't think I tried running with node > v10.
Will take a look and get back to you.

**Comment by danmindru** [comment]
Hey @NoWorries,

Did some spring cleaning and refactored things a little bit.
In version 5 that you can get now, all should work fine in node v12.

Tested from v9-v12 on macOS.

Let me know if it all works for you,
Dan
