### ISSUE TITLE
npm start ERROR

### ISSUE THREAD

**Issue by benjaminzanatta** [danmindru/responsive-html-email-signature#87]
Hi there, please provide some info about your enviornment before submiting this issue:
- device        : MacBook Pro mid 2015
- OS            : 10.15.6
- email client  : gmail
- node version  : v12.18.3
- npm version   : 6.14.6
- error message : 

```
> responsive-html-email-signature@6.0.1 start /Users/benjaminzanatta/Code/responsive-html-email-signature
> gulp

[09:04:23] Using gulpfile ~/Code/responsive-html-email-signature/gulpfile.js
[09:04:23] Starting 'default'...
[09:04:23] Starting 'run-pipeline'...
[09:04:23] Starting 'dupe'...
[09:04:23] Finished 'dupe' after 86 ms
[09:04:23] Starting 'less'...
[09:04:23] Finished 'less' after 10 ms
[09:04:23] Starting 'sass'...
[09:04:23] Starting 'dupe'...
[09:04:23] Finished 'dupe' after 44 ms
[09:04:23] Starting '<anonymous>'...
[09:04:23] Finished '<anonymous>' after 5.49 ms
[09:04:23] Finished 'sass' after 50 ms
[09:04:23] Starting 'postcss'...
[09:04:23] Finished 'postcss' after 65 ms
[09:04:23] Starting 'lint'...
[09:04:23] Finished 'lint' after 11 ms
[09:04:23] Starting 'build'...
[09:04:23] Finished 'build' after 8.43 ms
[09:04:23] Starting 'check-for-unused'...
[09:04:23] Finished 'check-for-unused' after 28 ms
[09:04:23] Finished 'run-pipeline' after 261 ms
[09:04:23] Starting '<anonymous>'...
[09:04:23] '<anonymous>' errored after 54 ms
[09:04:23] TypeError: cb.apply is not a function
    at /Users/benjaminzanatta/Code/responsive-html-email-signature/node_modules/npm/node_modules/graceful-fs/polyfills.js:267:18
    at FSReqCallback.oncomplete (fs.js:169:5)
    at FSReqCallback.callbackTrampoline (internal/async_hooks.js:120:14)
[09:04:23] 'default' errored after 317 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! responsive-html-email-signature@6.0.1 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the responsive-html-email-signature@6.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/benjaminzanatta/.npm/_logs/2020-08-11T13_04_23_711Z-debug.log
```

**Comment by DamianLedesma** [comment]
Having the same problem here. Does anybody knows how to solve it?

**Comment by joffreymougel** [comment]
Having the same problem too. @danmindru, do you have any idea of the problem ? and how to solve it ? or what to do in our side to deal with this issue ?

**Comment by joffreymougel** [comment]
**Same issue :** 

responsive-html-email-signature@6.0.1 start /Users/joffrey/Documents/Mail_Template/responsive-html-email-signature
gulp
[15:39:26] Using gulpfile ~/Documents/Mail_Template/responsive-html-email-signature/gulpfile.js
[15:39:26] Starting 'default'...
[15:39:26] Starting 'run-pipeline'...
[15:39:26] Starting 'dupe'...
[15:39:26] Finished 'dupe' after 43 ms
[15:39:26] Starting 'less'...
[15:39:26] Finished 'less' after 5.98 ms
[15:39:26] Starting 'sass'...
[15:39:26] Starting 'dupe'...
[15:39:27] Finished 'dupe' after 22 ms
[15:39:27] Starting ''...
[15:39:27] Finished '' after 4.65 ms
[15:39:27] Finished 'sass' after 27 ms
[15:39:27] Starting 'postcss'...
Browserslist: caniuse-lite is outdated. Please run the following command: npm update
[15:39:27] Finished 'postcss' after 42 ms
[15:39:27] Starting 'lint'...
[15:39:27] Finished 'lint' after 6.78 ms
[15:39:27] Starting 'build'...
[15:39:27] Finished 'build' after 8.39 ms
[15:39:27] Starting 'check-for-unused'...
[15:39:27] Finished 'check-for-unused' after 16 ms
[15:39:27] Finished 'run-pipeline' after 151 ms
[15:39:27] Starting ''...
[15:39:27] '' errored after 36 ms
[15:39:27] TypeError: cb.apply is not a function
at /Users/joffrey/Documents/Mail_Template/responsive-html-email-signature/node_modules/npm/node_modules/graceful-fs/polyfills.js:267:18
at FSReqCallback.oncomplete (fs.js:169:5)
at FSReqCallback.callbackTrampoline (internal/async_hooks.js:120:14)
[15:39:27] 'default' errored after 190 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! responsive-html-email-signature@6.0.1 start: gulp
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the responsive-html-email-signature@6.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/joffrey/.npm/_logs/2020-09-18T13_39_27_150Z-debug.log

——————————————————————————————————————————

**Details about the log file :**

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle responsive-html-email-signature@6.0.1~prestart: responsive-html-email-signature@6.0.1
6 info lifecycle responsive-html-email-signature@6.0.1~start: responsive-html-email-signature@6.0.1
7 verbose lifecycle responsive-html-email-signature@6.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle responsive-html-email-signature@6.0.1~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/joffrey/Documents/Mail_Template/responsive-html-email-signature/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle responsive-html-email-signature@6.0.1~start: CWD: /Users/joffrey/Documents/Mail_Template/responsive-html-email-signature
10 silly lifecycle responsive-html-email-signature@6.0.1~start: Args: [ '-c', 'gulp' ]
11 silly lifecycle responsive-html-email-signature@6.0.1~start: Returned: code: 1  signal: null
12 info lifecycle responsive-html-email-signature@6.0.1~start: Failed to exec start script
13 verbose stack Error: responsive-html-email-signature@6.0.1 start: `gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid responsive-html-email-signature@6.0.1
15 verbose cwd /Users/joffrey/Documents/Mail_Template/responsive-html-email-signature
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error responsive-html-email-signature@6.0.1 start: `gulp`
22 error Exit status 1
23 error Failed at the responsive-html-email-signature@6.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by danmindru** [comment]
Hi, thanks for the heads up.
It seems something’s broke with node v12.8 - I’ll look into it ASAP.
In the meantime, you could use node v11 to get around the issue.

**Comment by danmindru** [comment]
Should work now with node v12 to 14 :)

**Comment by joffreymougel** [comment]
Hi @danmindru 
Many thanks for your help !!
It work perfectly now :-)
